aws_zone_mapping: (( merge ))
aws_subnet_configs: (( merge ))

meta:
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest

networks:
- name: diego1
  type: manual
  subnets: (( aws_subnet_configs.diego1 ))
- name: diego2
  type: manual
  subnets: (( aws_subnet_configs.diego1 ))
- name: diego3
  type: manual
  subnets: (( aws_subnet_configs.diego1 ))

jobs:
  - name: cell_z1
    instances: 2
  - name: cell_z2
    instances: 2
  - name: etcd_z2
    instances: 0
  - name: etcd_z3
    instances: 0

compilation:
  cloud_properties:
    instance_type: c1.medium
    availability_zone: (( aws_zone_mapping.z1 ))

properties:
  diego:
    garden-linux:
      deny_networks:
        - 0.0.0.0/0
      allow_networks:
        - 10.10.0.2/32 # Amazon DNS
      disk_quota_enabled: ~

resource_pools:
  - name: brain_z1
    cloud_properties:
      instance_type: m2.2xlarge
      availability_zone: (( aws_zone_mapping.z1 ))
  - name: brain_z2
    cloud_properties:
      instance_type: m2.2xlarge
      availability_zone: (( aws_zone_mapping.z2 ))
  - name: brain_z3
    cloud_properties:
      instance_type: m2.2xlarge
      availability_zone: (( aws_zone_mapping.z3 ))
  - name: cc_bridge_z1
    cloud_properties:
      instance_type: c3.xlarge
      availability_zone: (( aws_zone_mapping.z1 ))
  - name: cc_bridge_z2
    cloud_properties:
      instance_type: c3.xlarge
      availability_zone: (( aws_zone_mapping.z2 ))
  - name: cc_bridge_z3
    cloud_properties:
      instance_type: c3.xlarge
      availability_zone: (( aws_zone_mapping.z3 ))
  - name: cell_z1
    cloud_properties:
      instance_type: m2.2xlarge
      availability_zone: (( aws_zone_mapping.z1 ))
  - name: cell_z2
    cloud_properties:
      instance_type: m2.2xlarge
      availability_zone: (( aws_zone_mapping.z2 ))
  - name: cell_z3
    cloud_properties:
      instance_type: m2.2xlarge
      availability_zone: (( aws_zone_mapping.z3 ))
  - name: etcd_z1
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( aws_zone_mapping.z1 ))
  - name: etcd_z2
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( aws_zone_mapping.z2 ))
  - name: etcd_z3
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( aws_zone_mapping.z3 ))
  - name: route_emitter_z1
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( aws_zone_mapping.z1 ))
  - name: route_emitter_z2
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( aws_zone_mapping.z2 ))
  - name: route_emitter_z3
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( aws_zone_mapping.z3 ))
