#!/bin/bash

set -e -x -u

stubs_path="${PWD}/${DEPLOYMENTS_DIR}/${DEPLOYMENT_NAME}/${STUBS_DIR}"
cf_deployment_name="cf-${DEPLOYMENT_NAME}"

pushd diego-release
  ./scripts/ci/bosh_setup

  bosh -n cleanup

  bosh -n upload stemcell bosh-stemcell/*.tgz --skip-if-exists

  bosh -n create release
  bosh -n upload release --rebase || true

  bosh download manifest ${cf_deployment_name} cf.yml
  ./scripts/generate-deployment-manifest ${INFRASTRUCTURE} cf.yml ${stubs_path}/* > diego-deployment.yml
  bosh deployment diego-deployment.yml

  ./scripts/ci/emit-datadog-deploy-event started ${cf_deployment_name} diego
  if bosh -n deploy; then
    ./scripts/ci/emit-datadog-deploy-event finished ${cf_deployment_name} diego
  else
    ./scripts/ci/emit-datadog-deploy-event failed ${cf_deployment_name} diego
    exit 1
  fi
popd

