meta:
  stemcell: (( merge ))

cf_config_for_diego: (( merge ))

name: (( cf_config_for_diego.cf_deployment_name "-diego" ))

director_uuid: (( merge ))

releases:
  - name: diego
    version: latest
  - name: cf
    version: latest

compilation:
  workers: 6
  network: diego1
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 5000-120000
  update_watch_time: 5000-120000

networks: (( merge ))

resource_pools:
  - name: brain_z1
    network: diego1
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: brain_z2
    network: diego2
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: brain_z3
    network: diego3
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: cc_bridge_z1
    network: diego1
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: cc_bridge_z2
    network: diego2
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: cc_bridge_z3
    network: diego3
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: cell_z1
    network: diego1
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: cell_z2
    network: diego2
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: cell_z3
    network: diego3
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: etcd_z1
    network: diego1
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: etcd_z2
    network: diego2
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: etcd_z3
    network: diego3
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: route_emitter_z1
    network: diego1
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: route_emitter_z2
    network: diego2
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: route_emitter_z3
    network: diego3
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

jobs:
  - name: etcd_z1
    templates:
      - name: etcd
        release: diego
    instances: 1
    persistent_disk: 1024
    resource_pool: etcd_z1
    networks:
      - name: diego1
        static_ips: (( static_ips(0) ))
    update:
      serial: true
      max_in_flight: 1

  - name: brain_z1
    templates:
      - name: consul_agent
        release: cf
      - name: auctioneer
        release: diego
      - name: converger
        release: diego
      - name: runtime_metrics_server
        release: diego
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: brain_z1
    networks:
      - name: diego1
    update:
      serial: true
    properties:
      metron_agent:
        zone: z1

  - name: cell_z1
    templates:
      - name: rep
        release: diego
      - name: consul_agent
        release: cf
      - name: executor
        release: diego
      - name: garden-linux
        release: diego
      - name: receptor
        release: diego
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: cell_z1
    networks:
      - name: diego1
    properties:
      metron_agent:
        zone: z1
      diego:
        rep:
          zone: z1
      consul:
        agent:
          services:
            - receptor

  - name: cc_bridge_z1
    templates:
      - name: stager
        release: diego
      - name: nsync
        release: diego
      - name: tps
        release: diego
      - name: file_server
        release: diego
      - name: consul_agent
        release: cf
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: cc_bridge_z1
    networks:
      - name: diego1
    properties:
      metron_agent:
        zone: z1
      consul:
        agent:
          services:
            - file_server
            - nsync
            - stager
            - tps

  - name: route_emitter_z1
    templates:
      - name: route_emitter
        release: diego
      - name: consul_agent
        release: cf
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: route_emitter_z1
    networks:
      - name: diego1
    properties:
      metron_agent:
        zone: z1

  - name: etcd_z2
    templates:
      - name: etcd
        release: diego
    instances: 1
    persistent_disk: 1024
    resource_pool: etcd_z2
    networks:
      - name: diego2
        static_ips: (( static_ips(0) ))
    update:
      serial: true
      max_in_flight: 1

  - name: brain_z2
    templates:
      - name: consul_agent
        release: cf
      - name: auctioneer
        release: diego
      - name: converger
        release: diego
      - name: runtime_metrics_server
        release: diego
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: brain_z2
    networks:
      - name: diego2
    update:
      serial: true
    properties:
      metron_agent:
        zone: z2

  - name: cell_z2
    templates:
      - name: rep
        release: diego
      - name: consul_agent
        release: cf
      - name: executor
        release: diego
      - name: garden-linux
        release: diego
      - name: receptor
        release: diego
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: cell_z2
    networks:
      - name: diego2
    properties:
      metron_agent:
        zone: z2
      diego:
        rep:
          zone: z2
      consul:
        agent:
          services:
            - receptor

  - name: cc_bridge_z2
    templates:
      - name: stager
        release: diego
      - name: nsync
        release: diego
      - name: tps
        release: diego
      - name: file_server
        release: diego
      - name: consul_agent
        release: cf
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: cc_bridge_z2
    networks:
      - name: diego2
    properties:
      metron_agent:
        zone: z2
      consul:
        agent:
          services:
            - file_server
            - nsync
            - stager
            - tps

  - name: route_emitter_z2
    templates:
      - name: route_emitter
        release: diego
      - name: consul_agent
        release: cf
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: route_emitter_z2
    networks:
      - name: diego2
    properties:
      metron_agent:
        zone: z2

  - name: etcd_z3
    templates:
      - name: etcd
        release: diego
    instances: 1
    persistent_disk: 1024
    resource_pool: etcd_z3
    networks:
      - name: diego3
        static_ips: (( static_ips(0) ))
    update:
      serial: true
      max_in_flight: 1

properties:
  # -- Properties below are used by the metron_agent job from cf-release --
  nats: # For metron_agent to talk to collector
    machines: (( cf_config_for_diego.nats.machines ))
    user: (( cf_config_for_diego.nats.user ))
    password: (( cf_config_for_diego.nats.password ))
    port: (( cf_config_for_diego.nats.port ))

  etcd: # For metron_agent to find loggregator
    machines: (( cf_config_for_diego.etcd.machines ))

  loggregator_endpoint:
    shared_secret: (( cf_config_for_diego.loggregator_endpoint.shared_secret ))

  syslog_daemon_config: ~

  # -- Property below is used by the consul_agent job from cf-release --
  consul:
    agent:
      servers:
        lan: (( cf_config_for_diego.consul.servers ))

  # -- Proerties below are used by jobs from diego-release --
  diego:
    # -- Global properties --
    ssl:
      skip_cert_verify: false

    # -- Job-specific properties --
    auctioneer:
      etcd:
        machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
      log_level: info

    converger:
      etcd:
        machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
      log_level: info

    executor:
      allow_privileged: ~
      drain_timeout_in_seconds: ~
      export_network_env_vars: ~
      garden: ~
      log_level: info

    etcd:
      machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))

    garden-linux: ~

    file_server:
      cc:
        base_url: (( cf_config_for_diego.cc.srv_api_uri ))
        basic_auth_password: (( cf_config_for_diego.cc.internal_api_password ))
        external_port: (( cf_config_for_diego.cc.external_port ))
        staging_upload_user: (( cf_config_for_diego.cc.staging_upload_user ))
        staging_upload_password: (( cf_config_for_diego.cc.staging_upload_password ))
      log_level: info

    nsync:
      diego_api_url: (( "http://" receptor.username ":" receptor.password "@receptor.service.consul:8888" ))
      cc:
        base_url: (( cf_config_for_diego.cc.srv_api_uri ))
        basic_auth_password: (( cf_config_for_diego.cc.internal_api_password ))
        external_port: (( cf_config_for_diego.cc.external_port ))
        staging_upload_user: (( cf_config_for_diego.cc.staging_upload_user ))
        staging_upload_password: (( cf_config_for_diego.cc.staging_upload_password ))
      etcd:
        machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
      lifecycle_bundles:
        buildpack/cflinuxfs2: buildpack_app_lifecycle/buildpack_app_lifecycle.tgz
        buildpack/lucid64: buildpack_app_lifecycle/buildpack_app_lifecycle.tgz
        buildpack/windows2012R2: windows_app_lifecycle/windows_app_lifecycle.tgz
        docker: docker_app_lifecycle/docker_app_lifecycle.tgz

    receptor:
      cors_enabled: false
      domain_names: ~
      etcd:
        machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
      nats:
        machines: (( cf_config_for_diego.nats.machines ))
        username: (( cf_config_for_diego.nats.user ))
        password: (( cf_config_for_diego.nats.password ))
        port: (( cf_config_for_diego.nats.port ))
      username: ""
      password: ""
      register_with_router: false
      log_level: info

    rep:
      etcd:
        machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
      log_level: info

    route_emitter:
      diego_api_url: (( "http://" receptor.username ":" receptor.password "@receptor.service.consul:8888" ))
      etcd:
        machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
      nats:
        machines: (( cf_config_for_diego.nats.machines ))
        username: (( cf_config_for_diego.nats.user ))
        password: (( cf_config_for_diego.nats.password ))
        port: (( cf_config_for_diego.nats.port ))
      log_level: info

    runtime_metrics_server:
      etcd:
        machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
      nats:
        machines: (( cf_config_for_diego.nats.machines ))
        username: (( cf_config_for_diego.nats.user ))
        password: (( cf_config_for_diego.nats.password ))
        port: (( cf_config_for_diego.nats.port ))

    stager:
      cc:
        base_url: (( cf_config_for_diego.cc.srv_api_uri ))
        basic_auth_password: (( cf_config_for_diego.cc.internal_api_password ))
        external_port: (( cf_config_for_diego.cc.external_port ))
        staging_upload_user: (( cf_config_for_diego.cc.staging_upload_user ))
        staging_upload_password: (( cf_config_for_diego.cc.staging_upload_password ))
      diego_api_url: (( "http://" receptor.username ":" receptor.password "@receptor.service.consul:8888" ))
      lifecycle_bundles:
        buildpack/cflinuxfs2: buildpack_app_lifecycle/buildpack_app_lifecycle.tgz
        buildpack/lucid64: buildpack_app_lifecycle/buildpack_app_lifecycle.tgz
        buildpack/windows2012R2: windows_app_lifecycle/windows_app_lifecycle.tgz
        docker: docker_app_lifecycle/docker_app_lifecycle.tgz
      log_level: info

    tps:
      cc:
        base_url: (( cf_config_for_diego.cc.srv_api_uri ))
        basic_auth_password: (( cf_config_for_diego.cc.internal_api_password ))
        external_port: (( cf_config_for_diego.cc.external_port ))
        staging_upload_user: (( cf_config_for_diego.cc.staging_upload_user ))
        staging_upload_password: (( cf_config_for_diego.cc.staging_upload_password ))
      diego_api_url: (( "http://" receptor.username ":" receptor.password "@receptor.service.consul:8888" ))
      log_level: info
