#!/bin/bash

set -e

templates=$(dirname $0)/../templates
templates_for_stubs=$(dirname $0)/../templates-for-stubs
stubs=$(dirname $0)/../stubs

function usage() {
  echo "    Usage:
    $0 <aws|bosh-lite> \\
      /path/to/cf-deployment-manifest.yml \\
      /path/to/director-uuid-stub.yml \\
      /path/to/property-overrides-stub.yml

    Ex:
    $0 aws \\
      ~/deployments/ketchup/cf.yml \\
      ~/workspaces/deployments-runtime/ketchup/stubs/director-uuid.yml \\
      ~/workspaces/deployments-runtime/ketchup/stubs/property-overrides.yml
"
  exit 1
}

if [ -z "$4" ]; then
  usage
fi

infrastructure=$1
cf_manifest=$2
director_uuid_stub=$3
property_overrides_stub=$4

if [ -z "$property_overrides_stub" ]; then
  usage
fi

if [ "$infrastructure" != "aws" ] && [ "$infrastructure" != "bosh-lite" ]; then
  usage
fi

if [ ! -f "$cf_manifest" ] || [ ! -f "$director_uuid_stub" ] || [ ! -f "$property_overrides_stub" ]; then
  usage
fi

if [ "$infrastructure" == "aws" ]; then
  spiff merge \
    $templates_for_stubs/iaas-settings.yml \
    $templates_for_stubs/aws-iaas-settings-internal.yml \
    $cf_manifest \
    > ${stubs}/aws-iaas-settings.yml
fi

spiff merge \
  $templates_for_stubs/cf-config-for-diego.yml \
  $templates_for_stubs/cf-config-for-diego-internal.yml \
  $cf_manifest \
  > ${stubs}/cf-config-for-diego.yml

spiff merge \
  $templates/deployment.yml \
  ${director_uuid_stub} \
  ${stubs}/${infrastructure}-iaas-settings.yml \
  ${stubs}/cf-config-for-diego.yml \
  ${property_overrides_stub}
