#!/bin/bash

set -e

templates=$(dirname $0)/../templates
stubs=$(dirname $0)/../stubs
templates_for_stubs=$(dirname $0)/../templates-for-stubs

infrastructure=$1
cf_manifest=$2

shift
shift

function usage() {
  echo "    Usage:
    $0 <aws|bosh-lite> /path/to/cf/deployment/manifest.yml [stubs...]

    Ex:
    $0 aws \\
      ~/deployments/ketchup/cf.yml \\
      ~/workspaces/deployments-runtime/ketchup/stubs/*
"
  exit 1
}

if [ -z "$cf_manifest" ]; then
  usage
fi

if [ "$infrastructure" != "aws" ] && [ "$infrastructure" != "bosh-lite" ]; then
  usage
fi

if [ ! -f "$cf_manifest" ] ; then
  usage
fi

if [ "$infrastructure" == "aws" ]; then
  spiff merge \
    $templates_for_stubs/aws-subnet-configs.yml \
    $templates_for_stubs/aws-subnet-configs-internal.yml \
    $cf_manifest \
    > ${stubs}/aws-subnet-configs.yml

  spiff merge \
    $templates_for_stubs/aws-zone-mapping.yml \
    $templates_for_stubs/aws-zone-mapping-internal.yml \
    $cf_manifest \
    > ${stubs}/aws-zone-mapping.yml

  spiff merge \
    ${templates_for_stubs}/aws.yml \
    ${stubs}/aws-subnet-configs.yml \
    ${stubs}/aws-zone-mapping.yml \
    > ${stubs}/aws.yml
fi

spiff merge \
  $templates_for_stubs/cf-config-for-diego.yml \
  $templates_for_stubs/cf-config-for-diego-internal.yml \
  $cf_manifest \
  > ${stubs}/cf-config-for-diego.yml

spiff merge \
  $templates/deployment.yml \
  ${stubs}/${infrastructure}.yml \
  ${stubs}/cf-config-for-diego.yml \
  "$@"
