#!/bin/bash

set -e

templates=$(dirname $0)/../templates

infrastructure=$1
cf_release=$2

function usage() {
  echo "usage:
  $0 <aws|bosh-lite> /path/to/cf-release [stubs...]

e.g.:
  $0 aws \\
    ~/workspace/cf-release \\
    ~/workspace/deployments-aws/ketchup/cf-aws-stub.yml \\
    ~/workspace/deployments-aws/ketchup/cf-shared-secrets.yml
"
  exit 1
}

if [ "$#" -lt 2 ]; then
  usage
fi

shift
shift

if [ "$infrastructure" != "aws" ] && [ "$infrastructure" != "bosh-lite" ]; then
  usage
fi

if [ -z "$cf_release" ]; then
  usage
fi

cf_shared_stub=/tmp/cf-diego-shared.yml
service_discovery_shared_stub=/tmp/service-discovery-shared.yml

cf_infrastructure=$infrastructure
if [ "$infrastructure" == "bosh-lite" ]; then
  cf_infrastructure="warden"
fi

spiff merge \
  $templates/cf-shared.yml \
  $templates/diego-cf-stub.yml \
  $cf_release/templates/cf-properties.yml \
  $cf_release/templates/cf-infrastructure-${cf_infrastructure}.yml \
  "$@" \
  > $cf_shared_stub

spiff merge \
  $templates/service-discovery-shared.yml \
  $templates/consul-and-etcd.yml \
  $templates/service-discovery-infrastructure-${infrastructure}.yml \
  "$@" \
  > $service_discovery_shared_stub

spiff merge \
  $templates/deployment.yml \
  $templates/infrastructure-${infrastructure}.yml \
  $cf_shared_stub \
  $service_discovery_shared_stub \
  "$@"
