#!/bin/bash

set -e

./scripts/generate-deployment-manifest \
  bosh-lite                            \
  ~/deployments/bosh-lite/cf.yml       \
  ~/deployments/bosh-lite/director.yml \
  stubs/bosh-lite-property-overrides.yml \
  > ~/deployments/bosh-lite/diego.yml

echo "WARNING: targeting BOSH-Lite director and setting Diego deployment manifest"
bosh target lite
bosh deployment ~/deployments/bosh-lite/diego.yml
bosh create release --force
bosh -n upload release
bosh -n deploy

pushd ./src/github.com/cloudfoundry-incubator/diego-acceptance-tests/

export CONFIG=`pwd`/integration_config.json
ginkgo -r -nodes=3 "$@" diego/
unset CONFIG

popd
